# Generated by Django 4.0.6 on 2022-07-22 18:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('website', models.FileField(blank=True, upload_to='cmsapp_sites/')),
                ('image', models.ImageField(blank=True, upload_to='cmsapp_images/')),
                ('siteicon', models.ImageField(blank=True, upload_to='cmsapp_icon/')),
                ('site_title', models.CharField(max_length=200)),
                ('slug', models.SlugField(editable=False, max_length=300, unique=True)),
                ('title', models.CharField(max_length=120)),
                ('body', models.TextField()),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
